### PR TITLE
Close XMLEventReader and XMLEventWriter to avoid shrinking of XML

### LINKED ISSUE #9: Do not shrink artifacts.xml during processsing
```
java.vm.version=25.172-b11
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation

OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"

```

After creating p2 proxy to "http://download.eclipse.org/releases/mars/" and attempt to use it in the local maven build it fails with error like:
```
[Fatal Error] :112850:13: XML document structures must start and end within the same entity.
[ERROR] Internal error: java.lang.RuntimeException: org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at https://.../repository/eclipse-mars. Unable to read repository at file:/C:/Users/.../.m2/repository/.cache/tycho/p2-repository-metadata/2116131570. XML document structures must start and end within the same entity. -> [Help 1]
```

The mentioned file "2116131570" appears to be zip with 1 file named "2116131570" inside it.

The inner file "2116131570" was an XML that ends with
```
      <property name="format" value="packed"></property>
      <pro
```
So, it was shrinked somethere during processing.

The solution is to work with XML processing more carefully, thanks to @afischer211 who found it. PR is following.

### PR DESCRIPTION
**Pull request by ruspl-afed**
On some PCs under Windows it shrinks the XML inside the JAR for p2 proxy, so it is impossible to use p2 proxy sites. The bug appears at least under Windows 8.1 JDK 1.8 x64

This pull request makes the following changes:
* XMLEventReader and XMLEventWriter are closed after usage to avoid shrinking of XML, based on solution suggested by @afischer211
* updated contributors accroding to [contributing guidelines](https://github.com/sonatype-nexus-community/nexus-repository-p2/blob/master/.github/CONTRIBUTING.md)

It relates to the following issue #s:
* Fixes #9

### CODE REVIEW

File: src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java [hunk 1]
```diff
@@ -90,10 +90,21 @@ public TempBlob removeMirrorUrlFromArtifactsXml(final TempBlob artifact,
           try (OutputStream xmlOut = xmlOutputStream(extension, tempFile)) {
             XMLInputFactory inputFactory = XMLInputFactory.newFactory();
             XMLOutputFactory outputFactory = XMLOutputFactory.newFactory();
-            XMLEventReader reader = inputFactory.createXMLEventReader(xmlIn);
-            XMLEventWriter writer = outputFactory.createXMLEventWriter(xmlOut);
-
-            streamXmlToWriterAndRemoveAbsoluteUrls(reader, writer);
+            XMLEventReader reader = null;
+            XMLEventWriter writer = null;
+            try {
```
Comment (mpiggott) [inline src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java]: I believe you could use a try-with resource block and simplify this.

Comment (ruspl-afed) [reply src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java]: `XMLEventReader` and `XMLEventWriter` are not `AutoCloseable` for some reason

**Comment by laeubi** [comment]
We are also hit by this bug, is there any plan to include and release the fix soon? Thsi happen on Linux as well!

**Comment by DarthHater** [comment]
Hi there! I'll try and take a gander at this today, thanks for the PR!

File: src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java (hunk 1 above)
Comment (DarthHater) [reply src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java]: They are intentionally not `AutoCloseable` from what I can tell.

File: src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java [hunk 2]
```diff
@@ -90,10 +90,22 @@ public TempBlob removeMirrorUrlFromArtifactsXml(final TempBlob artifact,
...
+            XMLEventReader reader = null;
+            XMLEventWriter writer = null;
+            //try-with-resources will be better here, but XMLEventReader and XMLEventWriter are not AutoCloseable
+            try {
+              reader = inputFactory.createXMLEventReader(xmlIn);
+              writer = outputFactory.createXMLEventWriter(xmlOut);
+              streamXmlToWriterAndRemoveAbsoluteUrls(reader, writer);
+              writer.flush();
+            } finally {
+              if (reader != null) {
```
Comment (DarthHater) [inline src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java]: It would likely be better to do a Yoda comparison here:

`if (null != reader)`

Prevents a typo at some point from setting the reader to null

File: src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java [hunk 3]
```diff
@@ -90,10 +90,22 @@ public TempBlob removeMirrorUrlFromArtifactsXml(final TempBlob artifact,
...
+                reader.close();
+              }
+              if (writer != null) {
```
Comment (DarthHater) [inline src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java]: It would likely be better to do a Yoda comparison here:

`if (null != writer)`

Prevents a typo at some point from setting the writer to null

File: src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java [hunk 4]
```diff
@@ -90,10 +90,22 @@ public TempBlob removeMirrorUrlFromArtifactsXml(final TempBlob artifact,
...
-
-            streamXmlToWriterAndRemoveAbsoluteUrls(reader, writer);
+            XMLEventReader reader = null;
+            XMLEventWriter writer = null;
+            //try-with-resources will be better here, but XMLEventReader and XMLEventWriter are not AutoCloseable
+            try {
+              reader = inputFactory.createXMLEventReader(xmlIn);
+              writer = outputFactory.createXMLEventWriter(xmlOut);
+              streamXmlToWriterAndRemoveAbsoluteUrls(reader, writer);
+              writer.flush();
```
Comment (DarthHater) [inline src/main/java/org/sonatype/nexus/repository/p2/internal/metadata/ArtifactsXmlAbsoluteUrlRemover.java]: I personally don't know the answer to this, but does writer.close() call flush()? That might make this redundant.
